// <auto-generated />
namespace FlightJournal.Web.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class InitialDatabaseCreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialDatabaseCreation));
        
        string IMigrationMetadata.Id
        {
            get { return "201408171336169_InitialDatabaseCreation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
