// <auto-generated />
namespace FlightJournal.Web.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class LastLogonTimeStamp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LastLogonTimeStamp));
        
        string IMigrationMetadata.Id
        {
            get { return "201504202209432_LastLogonTimeStamp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
