// <auto-generated />
namespace FlightJournal.Web.Migrations.FlightContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class FlightVersionDeletedDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FlightVersionDeletedDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201505062147469_FlightVersion-Deleted-Date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
