// <auto-generated />
namespace FlightJournal.Web.Migrations.FlightContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class ClubVisibility : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClubVisibility));
        
        string IMigrationMetadata.Id
        {
            get { return "201506232105012_Club-Visibility"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
