// <auto-generated />
namespace FlightJournal.Web.Migrations.FlightContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LocationextendedwithbitformarkingICAOspotasaOGNFlightLogAirfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LocationextendedwithbitformarkingICAOspotasaOGNFlightLogAirfield));
        
        string IMigrationMetadata.Id
        {
            get { return "201603292109197_Location extended with bit for marking ICAO spot as a OGN FlightLog Airfield"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
