// <auto-generated />
namespace FlightJournal.Web.Migrations.FlightContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddClubflagforusingAPRStakeoffandlanding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddClubflagforusingAPRStakeoffandlanding));
        
        string IMigrationMetadata.Id
        {
            get { return "202105141922276_Add Club flag for using APRS takeoff and landing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
