// <auto-generated />
namespace FlightJournal.Web.Migrations.FlightContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddinstructorfieldtoAppliedExercisetotracksoloflights : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddinstructorfieldtoAppliedExercisetotracksoloflights));
        
        string IMigrationMetadata.Id
        {
            get { return "202104121845010_Add instructor field to AppliedExercise to track solo flights"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
