// <auto-generated />
namespace FlightJournal.Web.Migrations.FlightContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Letclubsuseexportrecipient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Letclubsuseexportrecipient));
        
        string IMigrationMetadata.Id
        {
            get { return "202107051911406_Let clubs use export recipient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
