// <auto-generated />
namespace FlightJournal.Web.Migrations.FlightContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Extrafieldsforexportvalidationfortrainingprograms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Extrafieldsforexportvalidationfortrainingprograms));
        
        string IMigrationMetadata.Id
        {
            get { return "202108040827479_Extra fields for export validation for training programs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
