// <auto-generated />
namespace FlightJournal.Web.Migrations.FlightContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddcluboptiontomaskpilotidentitiesisuserisnotloggedinNSF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddcluboptiontomaskpilotidentitiesisuserisnotloggedinNSF));
        
        string IMigrationMetadata.Id
        {
            get { return "202305211838246_Add club option to mask pilot identities is user is not logged in (NSF)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
