// <auto-generated />
namespace FlightJournal.Web.Migrations.FlightContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddingPilotInTrainingProgram : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingPilotInTrainingProgram));
        
        string IMigrationMetadata.Id
        {
            get { return "202305061826179_Adding PilotInTrainingProgram"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
