// <auto-generated />
namespace FlightJournal.Web.Migrations.FlightContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addtrainingtablefortrackingofcompletedtrainings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addtrainingtablefortrackingofcompletedtrainings));
        
        string IMigrationMetadata.Id
        {
            get { return "202303252000296_Add training table for tracking of completed trainings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
